export const FETCH_GALLERY_START = 'FETCH_GALLERY_START';
export const FETCH_GALLERY_SUCCESS = 'FETCH_GALLERY_SUCCESS';
export const FETCH_GALLERY_FAILURE = 'FETCH_GALLERY_FAILURE';

export const FETCH_ITEM_BY_ID_START = 'FETCH_ITEM_BY_ID_START';
export const FETCH_ITEM_BY_ID_SUCCESS = 'FETCH_ITEM_BY_ID_SUCCESS';
export const FETCH_ITEM_BY_ID_FAILURE = 'FETCH_ITEM_BY_ID_FAILURE';

export const TOGGLE_MOBILE_MENU = 'TOGGLE_MOBILE_MENU';

export const FETCH_REVIEWS_START = 'FETCH_REVIEWS_START';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAILURE = 'FETCH_REVIEWS_FAILURE';

export const SEND_MESSAGE_START='SEND_MESSAGE_START';
export const SEND_MESSAGE_SUCCESS='SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE='SEND_MESSAGE_FAILURE';